#!/bin/bash
# MACE (Mendoza Automated CRYSTAL Engine) Example Commands
# After sourcing your shell config or activate_mace.sh

echo "MACE (Mendoza Automated CRYSTAL Engine) Example Commands"
echo "=============================="
echo ""
echo "D12 Creation (Crystal_d12):"
echo "  # Convert CIF files to D12"
echo "  cd /path/to/cif/files"
echo "  NewCifToD12.py  # or python $MACE_HOME/code/Crystal_d12/NewCifToD12.py"
echo ""
echo "  # Create D12 from optimized structure"
echo "  CRYSTALOptToD12.py material.out"
echo ""
echo "D3 Creation (Crystal_d3):"
echo "  # Create property calculations"
echo "  CRYSTALOptToD3.py material.out --calc-type BAND"
echo "  CRYSTALOptToD3.py material.out --calc-type DOSS"
echo "  CRYSTALOptToD3.py material.out --calc-type TRANSPORT"
echo ""
echo "Job Management (Job_Scripts):"
echo "  # Run comprehensive workflow"
echo "  run_workflow.py --interactive"
echo ""
echo "  # Submit jobs"
echo "  submitcrystal23.sh jobname"
echo "  submit_prop.sh property_calc"
echo ""
echo "  # Monitor calculations"
echo "  enhanced_queue_manager.py --status"
echo "  material_monitor.py --action dashboard"
echo ""
echo "Analysis (Post_Processing_Scripts):"
echo "  # Extract properties from outputs"
echo "  grab_properties.py"
echo ""
echo "Plotting (Plotting_Scripts):"
echo "  # Plot band structures"
echo "  autoBands.py material.BAND"
echo "  ipBANDS_V2.py material.BAND  # Interactive plotting"
echo ""
echo "  # Plot DOS"
echo "  ipDOS_V2.py material.DOSS    # Interactive plotting"
echo ""
echo "  # Plot phonon bands"
echo "  autoPhononBands.py material.f25"
echo ""
echo "  # Create overview PDF"
echo "  OverviewPDF.py"
echo ""
echo "Current environment:"
echo "  MACE_HOME=$MACE_HOME"
echo "  All script directories are in PATH"
